### ISSUE TITLE
Error on basic example

### ISSUE THREAD

**Issue by NAIJULU** [natalan/samsung-remote#1]
When performing basic example get the following error:

/home/naijulu/smart_tv/app.js:8
        throw new Error(err);
              ^
Error: Samsung Remote Client: Device is off or unreachable ECONNREFUSED
    at callback (/home/naijulu/smart_tv/app.js:8:15)
    at Socket.<anonymous> (/home/naijulu/smart_tv/node_modules/samsung-remote/lib/samsung-remote.js:94:13)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)

---

But if use only: remote.isAlive, the response is: TV is ALIVE!

Thanks for your help.

**Comment by pavelbinar** [comment]
`console.log('TV is ALIVE!');`

Is response for simple IP ping: https://github.com/natalan/samsung-remote/blob/master/lib/samsung-remote.js#L103

**Comment by rosch85** [comment]
i'm struggling with this too. Sending keys works perfect, but the isAlive call fails every time.

**Comment by neilshweky** [comment]
Having the same problem
